spring:
  datasource:
    url: jdbc:mysql://database-aws-instance-1.c4ea2opy3n1d.ap-east-1.rds.amazonaws.com:3306/w3a_metabase?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: bitdata
    password: 2021Mybitdata
    driver-class-name: com.mysql.cj.jdbc.Driver
